version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=SenhaAdmin2024!
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=carlosandrade
      - ME_CONFIG_BASICAUTH_PASSWORD=MinhaSenha2024!
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=SenhaAdmin2024!
    links:
      - mongodb
    networks:
      - mongo-compose-network  
      
networks: 
    mongo-compose-network:
      driver: bridge